version: '3'

networks:
  main:

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    networks:
      - main
    ports:
      - "5672:5672"
      - "15672:15672"

