# Routes
get_user:
  path: /users/{id}
  methods: GET
  controller: App\Controller\GetUserController

put_user:
  path: /users/{id}
  methods: PUT
  controller: App\Controller\PutUserController

delete_user:
  path: /users/{id}
  methods: DELETE
  controller: App\Controller\DeleteUserController