parameters:
    kernel.secret: yoursecretshouldbehere
    app_path: "../.."

framework:
    form: false
    assets: false
    session: false
    translator: false
    php_errors:
        log: false

command_bus:
    query_bus:
        middlewares:
            - App\Domain\Middleware\UpperCaseMiddleware

dbal:
    connections:
        users:
            driver: mysql
            host: localhost
            port: 3306
            user: root
            password: root
            database: users

# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    #
    # Controllers
    #
    App\Controller\:
        resource : "%app_path%/src/Controller/*"
        tags:
            - {name: controller.service_arguments}

    App\Domain\QueryHandler\:
        resource: "%app_path%/src/Domain/QueryHandler/*"
        tags:
            - {name: query_handler}

    App\Domain\CommandHandler\:
        resource: "%app_path%/src/Domain/CommandHandler/*"
        tags:
            - { name: command_handler }

    App\Domain\Model\InMemoryUserRepository:
    Infrastructure\DBAL\Model\DBALUserRepository:
    App\Domain\Model\UserRepository:
        alias: Infrastructure\DBAL\Model\DBALUserRepository
